// Generated by wavetables/generate_wavetables.py -- do not edit by hand.

#pragma once

namespace stankface {

// Wavetable storage layout. See wavetables/generate_wavetables.py.
inline constexpr int kNumWavetables  = 3;
inline constexpr int kNumFrames      = 8;
inline constexpr int kNumMipLevels   = 18;
inline constexpr int kFrameStride    = 9246;
inline constexpr int kTableStride    = 73968;

// Harmonics 1..kMipHarmonics[k] are present at level k.
inline constexpr int kMipHarmonics[kNumMipLevels] = { 512, 362, 256, 181, 128, 91, 64, 45, 32, 23, 16, 11, 8, 6, 4, 3, 2, 1 };

// Samples per cycle at level k. Each level is stored wrapped in guard
// samples -- one before, two after -- so the oscillator's four-point
// read needs no wrap check.
inline constexpr int kMipLength[kNumMipLevels] = { 2048, 1448, 1024, 724, 512, 364, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256 };

// Offset of level k within a frame.
inline constexpr int kMipOffset[kNumMipLevels] = { 1, 2052, 3503, 4530, 5257, 5772, 6139, 6398, 6657, 6916, 7175, 7434, 7693, 7952, 8211, 8470, 8729, 8988 };

extern const float kWavetableData[kNumWavetables * kTableStride];
extern const char* const kWavetableNames[kNumWavetables];

// Sample 0 of one frame's mip level. Indices -1 to length + 1 are
// readable, courtesy of the guard samples.
inline const float* wavetableFrame(int table, int frame, int mip)
{
    return kWavetableData + table * kTableStride
                          + frame * kFrameStride
                          + kMipOffset[mip];
}

} // namespace stankface
